disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_unwrapping

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message

included:
  - Sources

excluded:
  - Carthage
  - Pods
  - build

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

reporter: xcode 